function J = element_jacobian_wedge(in1,in2)
%ELEMENT_JACOBIAN_WEDGE
%    J = ELEMENT_JACOBIAN_WEDGE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    02-Apr-2019 22:59:20

eta = in1(2,:);
ji = in1(1,:);
mu = in1(3,:);
x1 = in2(1);
x2 = in2(2);
x3 = in2(3);
x4 = in2(4);
x5 = in2(5);
x6 = in2(6);
y1 = in2(7);
y2 = in2(8);
y3 = in2(9);
y4 = in2(10);
y5 = in2(11);
y6 = in2(12);
z1 = in2(13);
z2 = in2(14);
z3 = in2(15);
z4 = in2(16);
z5 = in2(17);
z6 = in2(18);
t2 = mu.*(1.0./2.0);
t3 = t2-1.0./2.0;
t4 = t2+1.0./2.0;
t5 = t3.*x1;
t6 = t3.*y1;
t7 = t3.*z1;
t8 = eta+ji-1.0;
J = reshape([t5-t3.*x2-t4.*x4+t4.*x5,t5-t3.*x3-t4.*x4+t4.*x6,eta.*x3.*(-1.0./2.0)+eta.*x6.*(1.0./2.0)-ji.*x2.*(1.0./2.0)+ji.*x5.*(1.0./2.0)+t8.*x1.*(1.0./2.0)-t8.*x4.*(1.0./2.0),t6-t3.*y2-t4.*y4+t4.*y5,t6-t3.*y3-t4.*y4+t4.*y6,eta.*y3.*(-1.0./2.0)+eta.*y6.*(1.0./2.0)-ji.*y2.*(1.0./2.0)+ji.*y5.*(1.0./2.0)+t8.*y1.*(1.0./2.0)-t8.*y4.*(1.0./2.0),t7-t3.*z2-t4.*z4+t4.*z5,t7-t3.*z3-t4.*z4+t4.*z6,eta.*z3.*(-1.0./2.0)+eta.*z6.*(1.0./2.0)-ji.*z2.*(1.0./2.0)+ji.*z5.*(1.0./2.0)+t8.*z1.*(1.0./2.0)-t8.*z4.*(1.0./2.0)],[3, 3]);
