function N3 = shape_functions_wedge(in1)
%SHAPE_FUNCTIONS_WEDGE
%    N3 = SHAPE_FUNCTIONS_WEDGE(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    05-Apr-2019 09:20:27

eta = in1(2,:);
ji = in1(1,:);
mu = in1(3,:);
t2 = mu./2.0;
t3 = t2-1.0./2.0;
t4 = eta+ji-1.0;
t5 = t2+1.0./2.0;
t6 = t3.*t4;
t7 = ji.*t5;
t8 = eta.*t5;
N3 = reshape([t6,0.0,0.0,0.0,t6,0.0,0.0,0.0,t6,-ji.*t3,0.0,0.0,0.0,-ji.*t3,0.0,0.0,0.0,-ji.*t3,-eta.*t3,0.0,0.0,0.0,-eta.*t3,0.0,0.0,0.0,-eta.*t3,-t4.*t5,0.0,0.0,0.0,-t4.*t5,0.0,0.0,0.0,-t4.*t5,t7,0.0,0.0,0.0,t7,0.0,0.0,0.0,t7,t8,0.0,0.0,0.0,t8,0.0,0.0,0.0,t8],[3,18]);
