function N_jem = shape_jacobian_wedge(in1)
%SHAPE_JACOBIAN_WEDGE
%    N_JEM = SHAPE_JACOBIAN_WEDGE(IN1)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    02-Apr-2019 23:05:03

eta = in1(2,:);
ji = in1(1,:);
mu = in1(3,:);
t2 = mu.*(1.0./2.0);
t3 = t2-1.0./2.0;
t4 = -t2+1.0./2.0;
t5 = -t2-1.0./2.0;
t6 = t2+1.0./2.0;
t7 = ji.*(1.0./2.0);
t8 = eta.*(1.0./2.0);
N_jem = reshape([t3,t3,t7+t8-1.0./2.0,t4,0.0,-t7,0.0,t4,-t8,t5,t5,-t7-t8+1.0./2.0,t6,0.0,t7,0.0,t6,t8],[3, 6]);
