function Naux = shape_functions(in1)
%SHAPE_FUNCTIONS
%    NAUX = SHAPE_FUNCTIONS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    20-Mar-2019 12:35:28

eta = in1(2,:);
ji = in1(1,:);
mu = in1(3,:);
t2 = ji./8.0;
t3 = eta-1.0;
t4 = mu-1.0;
t5 = t2+1.0./8.0;
t6 = t2-1.0./8.0;
t7 = eta+1.0;
t8 = mu+1.0;
t9 = t3.*t4.*t5;
t10 = t4.*t6.*t7;
t11 = t3.*t6.*t8;
t12 = t5.*t7.*t8;
Naux = reshape([-t3.*t4.*t6,0.0,0.0,0.0,-t3.*t4.*t6,0.0,0.0,0.0,-t3.*t4.*t6,t9,0.0,0.0,0.0,t9,0.0,0.0,0.0,t9,-t4.*t5.*t7,0.0,0.0,0.0,-t4.*t5.*t7,0.0,0.0,0.0,-t4.*t5.*t7,t10,0.0,0.0,0.0,t10,0.0,0.0,0.0,t10,t11,0.0,0.0,0.0,t11,0.0,0.0,0.0,t11,-t3.*t5.*t8,0.0,0.0,0.0,-t3.*t5.*t8,0.0,0.0,0.0,-t3.*t5.*t8,t12,0.0,0.0,0.0,t12,0.0,0.0,0.0,t12,-t6.*t7.*t8,0.0,0.0,0.0,-t6.*t7.*t8,0.0,0.0,0.0,-t6.*t7.*t8],[3,24]);
